In [1]:
import pandas as pd
import numpy as np
import keras
import tensorflow
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

In [2]:
data = pd.read_csv("train.txt",sep=";")
data.columns = ["Text","Emotions"]
print(data.head())

                                                Text Emotions
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness


In [3]:
texts = data["Text"].tolist()
labels = data["Emotions"].tolist()

In [4]:
texts

['i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake',
 'im grabbing a minute to post i feel greedy wrong',
 'i am ever feeling nostalgic about the fireplace i will know that it is still on the property',
 'i am feeling grouchy',
 'ive been feeling a little burdened lately wasnt sure why that was',
 'ive been taking or milligrams or times recommended amount and ive fallen asleep a lot faster but i also feel like so funny',
 'i feel as confused about life as a teenager or as jaded as a year old man',
 'i have been with petronas for years i feel that petronas has performed well and made a huge profit',
 'i feel romantic too',
 'i feel like i have to make the suffering i m seeing mean something',
 'i do feel that running is a divine experience and that i can expect to have some type of spiritual encounter',
 'i think it s the easiest time of year to feel dissatisfied',
 'i feel low energy i m just thirsty',
 'i have immense sympath

In [5]:
labels

['sadness',
 'anger',
 'love',
 'anger',
 'sadness',
 'surprise',
 'fear',
 'joy',
 'love',
 'sadness',
 'joy',
 'anger',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'sadness',
 'sadness',
 'fear',
 'anger',
 'fear',
 'joy',
 'joy',
 'anger',
 'sadness',
 'sadness',
 'sadness',
 'anger',
 'joy',
 'joy',
 'fear',
 'surprise',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'love',
 'joy',
 'anger',
 'joy',
 'sadness',
 'anger',
 'fear',
 'joy',
 'sadness',
 'sadness',
 'surprise',
 'joy',
 'joy',
 'joy',
 'love',
 'fear',
 'fear',
 'surprise',
 'anger',
 'anger',
 'sadness',
 'love',
 'joy',
 'sadness',
 'sadness',
 'joy',
 'sadness',
 'sadness',
 'sadness',
 'joy',
 'joy',
 'joy',
 'anger',
 'sadness',
 'anger',
 'anger',
 'anger',
 'joy',
 'joy',
 'joy',
 'joy',
 'sadness',
 'fear',
 'love',
 'anger',
 'sadness',
 'anger',
 'love',
 'sadness',
 'joy',
 'joy',
 'sadness',
 'anger',
 'love',
 'joy',
 'joy',
 'joy'

In [6]:
# Tokenize the text data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

In [7]:
sequences = tokenizer.texts_to_sequences(texts)
sequences

[[1,
  39,
  100,
  59,
  7,
  14,
  493,
  4,
  14,
  3495,
  552,
  31,
  59,
  60,
  127,
  147,
  75,
  1479,
  3,
  21,
  1254],
 [16, 3059, 6, 1148, 4, 285, 1, 2, 494, 437],
 [1, 23, 164, 7, 664, 26, 5, 4157, 1, 58, 46, 8, 12, 21, 71, 29, 5, 3496],
 [1, 23, 7, 1064],
 [72, 47, 7, 6, 55, 520, 318, 327, 157, 160, 8, 19],
 [72,
  47,
  328,
  34,
  7400,
  34,
  195,
  7401,
  887,
  3,
  72,
  2474,
  1383,
  6,
  158,
  1884,
  18,
  1,
  116,
  2,
  13,
  14,
  454],
 [1, 2, 28, 438, 26, 77, 28, 6, 1685, 34, 28, 759, 28, 6, 192, 266, 373],
 [1,
  20,
  47,
  24,
  5259,
  15,
  214,
  1,
  2,
  8,
  5259,
  98,
  5260,
  134,
  3,
  131,
  6,
  1037,
  4158],
 [1, 2, 665, 93],
 [1, 2, 13, 1, 20, 4, 79, 5, 732, 1, 92, 543, 303, 83],
 [1,
  38,
  2,
  8,
  482,
  21,
  6,
  529,
  439,
  3,
  8,
  1,
  39,
  919,
  4,
  20,
  68,
  839,
  9,
  1885,
  3060],
 [1, 69, 12, 89, 5, 5261, 51, 9, 192, 4, 2, 609],
 [1, 2, 338, 455, 1, 92, 31, 4159],
 [1,
  20,
  4160,
  1686,
  24,
  5,
 

In [8]:
max_length = max([len(seq) for seq in sequences])
padded_sequences = pad_sequences(sequences, maxlen=max_length)

In [9]:
padded_sequences

array([[   0,    0,    0, ...,    3,   21, 1254],
       [   0,    0,    0, ...,    2,  494,  437],
       [   0,    0,    0, ...,   29,    5, 3496],
       ...,
       [   0,    0,    0, ...,    3,  101, 1331],
       [   0,    0,    0, ...,  339,    8,   42],
       [   0,    0,    0, ...,   25, 3585,   12]])

In [10]:
len(padded_sequences[0])

66

In [11]:
data['Emotions'].value_counts()

Emotions
joy         5362
sadness     4665
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [12]:
# Encode the string labels to integers
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

In [13]:
labels

array([4, 0, 3, ..., 2, 0, 4], dtype=int64)

In [14]:

# One-hot encode the labels
one_hot_labels = keras.utils.to_categorical(labels)

In [15]:
one_hot_labels

array([[0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [16]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, 
                                                one_hot_labels, 
                                                test_size=0.2,random_state=42)

In [17]:
one_hot_labels[0]

array([0., 0., 0., 0., 1., 0.], dtype=float32)

In [18]:
# Define the model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, 
                    output_dim=128, input_length=max_length))
model.add(Flatten())
model.add(Dense(units=128, activation="relu"))
model.add(Dense(units=len(one_hot_labels[0]), activation="softmax"))

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/10
400/400 [==============================] - 19s 45ms/step - loss: 1.3506 - accuracy: 0.4837 - val_loss: 0.8911 - val_accuracy: 0.6994
Epoch 2/10
400/400 [==============================] - 16s 41ms/step - loss: 0.3577 - accuracy: 0.8865 - val_loss: 0.5326 - val_accuracy: 0.8225
Epoch 3/10
400/400 [==============================] - 19s 48ms/step - loss: 0.0612 - accuracy: 0.9840 - val_loss: 0.5622 - val_accuracy: 0.8297
Epoch 4/10
400/400 [==============================] - 17s 43ms/step - loss: 0.0289 - accuracy: 0.9941 - val_loss: 0.5718 - val_accuracy: 0.8306
Epoch 5/10
400/400 [==============================] - 15s 38ms/step - loss: 0.0175 - accuracy: 0.9962 - val_loss: 0.6287 - val_accuracy: 0.8263
Epoch 6/10
400/400 [==============================] - 15s 38ms/step - loss: 0.0170 - accuracy: 0.9966 - val_loss: 0.6425 - val_accuracy: 0.8303
Epoch 7/10
400/400 [==============================] - 15s 38ms/step - loss: 0.0153 - accuracy: 0.9969 - val_loss: 0.6708 - val_accuracy:

In [19]:
input_text = "i am ever feeling nostalgic about the fireplace i will know that it is still on the property"

# Preprocess the input text
input_sequence = tokenizer.texts_to_sequences([input_text])
padded_input_sequence = pad_sequences(input_sequence, maxlen=max_length)
prediction = model.predict(padded_input_sequence)
predicted_label = label_encoder.inverse_transform([np.argmax(prediction[0])])
print(predicted_label[0])

1/1 [==============================] - 0s 96ms/step
love


In [20]:
input_text = "im feeling rather rotten so im not very ambitious right now"

# Preprocess the input text
input_sequence = tokenizer.texts_to_sequences([input_text])
padded_input_sequence = pad_sequences(input_sequence, maxlen=max_length)
prediction = model.predict(padded_input_sequence)
predicted_label = label_encoder.inverse_transform([np.argmax(prediction[0])])
print(predicted_label[0])

1/1 [==============================] - 0s 15ms/step
sadness


In [21]:
print("The End")

The End
